"""add created_at and update_at in livros table

Revision ID: 5257d1859b7c
Revises: ff60df26779b
Create Date: 2025-10-25 15:08:14.148396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5257d1859b7c'
down_revision: Union[str, Sequence[str], None] = 'ff60df26779b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('livros', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livros', 'updated_at')
    op.drop_column('livros', 'created_at')
    # ### end Alembic commands ###
